"""Build docs/qacrs/RESULTS_v4_v5.md + fig5 from result files only, and docs/qacrs/RESEARCH_LOG.md from git history.

    cd backend && python -m qacrs.report_v45
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from qacrs import figures_v3 as F

R = Path(__file__).parent / "results"
DOCS = Path(__file__).resolve().parents[2] / "docs" / "qacrs"


def j(p):
    return json.loads((R / p).read_text())


def pct(x):
    return f"{100 * x:.1f}%"


def ci(c):
    return f"{pct(c[0])}–{pct(c[1])}"


def fig_iterations(ho, v5, esc3):
    stages = [("v2\ndev (40)", esc3["summary"]["q_acrs"]["silent_failures"] + esc3["summary"]["q_acrs"]["escalated"], 40, "before any gate"),
              ("v3 gate\ndev (40)", esc3["summary"]["q_acrs"]["silent_failures"], 40, "designed here"),
              ("v3 gate\nheld-out 9001", ho["summary"]["q_acrs"]["silent_failures"], ho["tests_heldout"]["n"], "new failure class found"),
              ("v5 gate\nfresh 9002", v5["confirmatory_9002"]["gate_comparison_q_acrs"]["v5"]["silent"], v5["confirmatory_9002"]["n"], "confirmatory test")]
    from qacrs.stats import wilson
    fig, ax = plt.subplots(figsize=(7.6, 3.9))
    xs = range(len(stages))
    rates = [100 * k / n for _, k, n, _ in stages]
    errs = [[100 * (k / n - wilson(k, n)[0]) for _, k, n, _ in stages], [100 * (wilson(k, n)[1] - k / n) for _, k, n, _ in stages]]
    cols = [F.SERIOUS, F.GOOD, F.SERIOUS, F.GOOD]
    ax.bar(xs, rates, color=cols, width=0.55, yerr=errs, capsize=4, ecolor=F.INK2)
    for x, (lab, k, n, note) in zip(xs, stages):
        ax.text(x, 100 * wilson(k, n)[1] + 1.2, f"{k}/{n}\n{note}", ha="center", fontsize=8, color=F.INK2)
    ax.set_xticks(list(xs), [s[0] for s in stages]); ax.set_ylabel("Silent failures (% of scenarios)")
    ax.set_ylim(0, max(100 * wilson(k, n)[1] for _, k, n, _ in stages) + 8); ax.grid(axis="x", visible=False)
    ax.set_axisbelow(True)
    ax.set_title("Design → test → find failure → fix → re-test on fresh data")
    F.foot(fig, "Q-ACRS silent failures (threat not contained and not escalated). Bars: rate; whiskers: Wilson 95% CI. "
                "Stage 1 counts all v2 failures (no gate existed). Simulation.", y=-0.06)
    F.save(fig, "fig5_iterations.png")


def results_md(ho, v5, lab, esc3) -> str:
    t, c5 = ho["tests_heldout"], v5["confirmatory_9002"]
    t5 = c5["tests"]; g = c5["gate_comparison_q_acrs"]; s = lab["summary"]
    L = ["# Q-ACRS — Results v4 and v5", "",
         "> Generated by `python -m qacrs.report_v45` from `backend/qacrs/results/v4` and `v5`. Criteria fixed in advance in "
         "`PREREGISTRATION_v4.md` and `PREREGISTRATION_v5.md`. Simulation unless stated.", "",
         "## v4 — Held-out scenarios (seed 9001), confirmatory statistics", "",
         f"{t['n']} scenarios after dropping {len(ho['meta']['settings']['dropped_duplicates'])} duplicates.", "",
         "| Method | Contained (Wilson 95%) | Escalated | Silent | Rejected (unsafe) | Services down |", "|---|---|---|---|---|---|"]
    for m, name in (("full_isolation", "Full isolation"), ("full_isolation_safe", "Full isolation (safe)"),
                    ("per_machine", "Per-machine rule"), ("q_acrs", "Q-ACRS + v3 gate")):
        x = ho["summary"][m]; r = t["rates_wilson95"][m]
        L.append(f"| {name} | {x['contained']} ({pct(r['contained'][0])}, {ci(r['contained'][1])}) | {x['escalated']} | "
                 f"{x['silent_failures']} | {x['status_counts']['REJECTED']} | {x['services_down']} |")
    h1, h2, h3, h4 = t["H1_v3"], t["H2_silent_failures"], t["H3_services_down_wilcoxon_one_sided"], t["H4_containment_mcnemar"]
    b = t["bootstrap95"]
    L += ["", "| Hypothesis | Result | Verdict |", "|---|---|---|",
          f"| H1-v3 (≥80% containment of safe full isolation AND fewer services down) | ratio {h1['ratio']}; services {h1['q_services_down']} vs {h1['safe_full_services_down']} | {'supported' if h1['supported'] else '**not supported**'} |",
          f"| H2 (silent failures: Wilson upper ≤ 2%) | {h2['count']}/{t['n']} = {pct(h2['rate'])}, CI {ci(h2['wilson95'])} | {'supported' if h2['supported'] else '**not supported**'} |",
          f"| H3 (fewer services down per scenario, Wilcoxon one-sided) | p = {h3['p']:.1e} ({h3['nonzero_pairs']} non-tied pairs) | {'supported' if h3['supported'] else 'not supported'} |",
          f"| H4 (containment differs, exact McNemar) | Q-ACRS-only {h4['q_only_contained']} vs safe-full-only {h4['safe_full_only_contained']}, p = {h4['p_two_sided']:.1e} | {h4['direction']} |",
          "", f"Bootstrap 95% CI (Q-ACRS − safe full isolation): containment rate {b['containment_rate_q_minus_safe_full'][0]:+.3f} to "
          f"{b['containment_rate_q_minus_safe_full'][1]:+.3f}; services down per scenario {b['services_down_per_scenario_q_minus_safe_full'][0]:+.3f} to "
          f"{b['services_down_per_scenario_q_minus_safe_full'][1]:+.3f}.", "",
          "**What failed and why:** every silent failure had **both twins of a service hacked**: Q-ACRS isolated one twin to keep "
          "the service up and left the other restricted (open path to the database or high risk). The v3 gate did not cover "
          "this case → v5.", "",
          "## v4 — Real-kernel validation (Linux iptables + real TCP, isolated container)", "",
          f"{s['runs']} runs ({s['scenarios']} scenarios × Q-ACRS and safe full isolation), **{s['checks']} real connection checks, "
          f"{s['mismatches']} mismatches → agreement {pct(s['agreement'])}** (H5 {'supported' if s['H5_supported'] else 'not supported'}). "
          f"Checks cover the attacker channel, every service path, every lateral path to a critical server, and every healthy "
          f"machine; both blocked and open outcomes are tested. Median time to apply a policy: {s['execute_ms_median']} ms. "
          f"{s['notes_hacked_critical_target_links']} links into an already-hacked critical server were logged separately "
          "(outside the C1 definition, by design). Executor outcomes: " +
          ", ".join(f"{k} {v}" for k, v in sorted(s["executor_status_counts"].items())) + ".", "",
          "Scope: one Linux kernel, loopback addresses; validates decision → firewall rules → traffic, not detection or a hospital network.", "",
          "## v5 — Twin-dilemma gate (G3), confirmed on a fresh held-out set (seed 9002)", "",
          "| Set | n | Silent failures, v3 gate | Silent failures, v5 gate (Wilson 95%) | Escalation rate v3 → v5 | H2-v5 |", "|---|---|---|---|---|---|"]
    for key, lab_ in (("confirmatory_9002", "**9002 (confirmatory, never seen)**"), ("secondary_9001", "9001 (G3 designed here)"),
                      ("secondary_dev", "development")):
        x = v5[key]; gg = x["gate_comparison_q_acrs"]
        L.append(f"| {lab_} | {x['n']} | {gg['v3']['silent']} | {gg['v5']['silent']} ({ci(gg['v5']['silent_wilson95'])}) | "
                 f"{pct(gg['v3']['escalation_rate'])} → {pct(gg['v5']['escalation_rate'])} | {'supported' if x['H2_v5_supported'] else 'not supported (n too small for the bound)' if x['n'] < 100 else 'not supported'} |")
    L += ["", f"On 9002: H1-v3 ratio {t5['H1_v3']['ratio']} → {'supported' if t5['H1_v3']['supported'] else 'not supported'}; "
          f"H3 p = {t5['H3_services_down_wilcoxon_one_sided']['p']:.1e}; McNemar: Q-ACRS-only {t5['H4_containment_mcnemar']['q_only_contained']} vs "
          f"safe-full-only {t5['H4_containment_mcnemar']['safe_full_only_contained']}.", "",
          f"**Cost of G3:** escalations rise by {pct(g['v5']['escalation_rate'] - g['v3']['escalation_rate'])} of incidents; overall {pct(g['v5']['escalation_rate'])} of held-out incidents need a human "
          "decision with a concrete recommended action. That is the price of never failing silently, and it is reported as a limitation.", "",
          f"**H1 across sets:** containment ratio {t['H1_v3']['ratio']} (9001) vs {t5['H1_v3']['ratio']} (9002) — borderline around the 80% threshold. Q-ACRS contains "
          "fewer incidents automatically than safe full isolation in every set (McNemar), while taking down zero services.", "",
          "![iterations](figures/fig5_iterations.png)", ""]
    return "\n".join(L)


def research_log() -> str:
    out = subprocess.check_output(["git", "log", "--reverse", "--date=format:%Y-%m-%d %H:%M",
                                   "--format=%h|%ad|%s", "--", "backend/qacrs", "docs/qacrs", "backend/tests"],
                                  cwd=DOCS.parents[1], text=True)
    L = ["# Research log (generated from git history)", "",
         "> Generated by `python -m qacrs.report_v45`. Every entry is a commit; dates are commit dates (UTC offset of the "
         "machine that made it). Pre-registration commits come before the code and results they govern.", "",
         "| Date | Commit | What |", "|---|---|---|"]
    for line in out.strip().splitlines():
        h, d, s = line.split("|", 2)
        L.append(f"| {d} | `{h}` | {s.replace('|', '/')} |")
    return "\n".join(L) + "\n"


def main():
    ho, v5, lab, esc3 = j("v4/heldout.json"), j("v5/v5_heldout.json"), j("v4/sandbox_lab.json"), j("v3/escalation.json")
    fig_iterations(ho, v5, esc3)
    (DOCS / "RESULTS_v4_v5.md").write_text(results_md(ho, v5, lab, esc3))
    (DOCS / "RESEARCH_LOG.md").write_text(research_log())
    print("Saved: docs/qacrs/RESULTS_v4_v5.md, RESEARCH_LOG.md")


if __name__ == "__main__":
    main()
