"""Build docs/qacrs/RESULTS_v3.md from the v3 result files only (no number typed by hand).

    cd backend && python -m qacrs.report_v3
"""
from __future__ import annotations

import json
from pathlib import Path

R = Path(__file__).parent / "results" / "v3"
DOC = Path(__file__).resolve().parents[2] / "docs" / "qacrs" / "RESULTS_v3.md"
NAMES = {"full_isolation": "Full isolation", "full_isolation_safe": "Full isolation (safe)",
         "per_machine": "Per-machine rule", "q_acrs": "Q-ACRS"}


def j(p):
    f = R / p
    return json.loads(f.read_text()) if f.exists() else None


def rng(s, pct=False):
    f = (lambda v: f"{100 * v:.1f}%") if pct else (lambda v: f"{v:g}")
    return f"{f(s['median'])} (range {f(s['min'])}–{f(s['max'])})"


def build() -> str:
    esc, sen, sca = j("escalation.json"), j("sensitivity.json"), j("scaling.json")
    qs = j("qaoa_seeds_summary.json")
    ibm = sorted((R / "ibm").glob("*_run.json")) if (R / "ibm").exists() else []
    blind = sorted((R / "independent").glob("*.json")) if (R / "independent").exists() else []
    L = ["# Q-ACRS — Results v3", "",
         "> Generated by `python -m qacrs.report_v3` from `backend/qacrs/results/v3/`. Criteria were fixed in advance "
         "in `docs/qacrs/PREREGISTRATION_v3.md`. All results are **simulation** unless a section says hardware.", ""]

    # E1
    s = esc["summary"]; h = esc["h1_v3_dev_set"]
    L += ["## E1 — Escalation gate (40 development scenarios)", "",
          "| Method | Contained | …needs 2 approvers | Escalated (action given) | Silent failures | Rejected (unsafe) | Services down |",
          "|---|---|---|---|---|---|---|"]
    for k, n in NAMES.items():
        x = s[k]; c = x["status_counts"]
        L.append(f"| {n} | {x['contained']} | {c['CONTAINED_PENDING_APPROVAL']} | {x['escalated']} | "
                 f"{x['silent_failures']} | {c['REJECTED']} | {x['services_down']} |")
    L += ["", f"Q-ACRS: {s['q_acrs']['silent_failures']} silent failures (v2 had 8), with "
          f"{s['q_acrs']['escalation_actions']} concrete human actions across {s['q_acrs']['escalated']} scenarios. "
          "**Caveat (pre-registered):** the gate was designed after seeing these scenarios, so this shows the gate "
          "works as built, not that it generalises.", "",
          f"H1-v3 on the development set (not a new test): containment ratio {h['containment_ratio']}, fewer services "
          f"down: {h['fewer_services_down']} → {'supported' if h['H1_v3_supported'] else 'not supported'}.", "",
          "![outcomes](figures/fig2_outcomes.png)", ""]

    # E2
    v = sen["verdict"]; b = sen["baseline"]
    L += ["## E2 — Weight sensitivity and trade-off", "",
          "| Factor | Levels tested | Max decisions changed within ±30% | First level that changes any decision | Verdict |",
          "|---|---|---|---|---|"]
    lv = ", ".join(f"{x:g}" for x in sen["meta"]["settings"]["levels"])
    for k, x in v.items():
        L.append(f"| `{k}` | {lv} | {x['max_changed_within_30pct']}/40 | "
                 f"{x['closest_level_with_any_change'] or 'none (up to ±50%)'} | {'robust' if x['robust'] else 'sensitive'} |")
    L += ["", "Availability weight λ (service values and disruption scaled together):", "",
          "| λ | Contained | Escalated | Silent | Services down | Risk left | Decisions changed vs λ=1 |",
          "|---|---|---|---|---|---|---|"]
    for p in sen["pareto"]:
        L.append(f"| {p['lambda']:g} | {p['contained']} | {p['escalated']} | {p['silent_failures']} | "
                 f"{p['services_down']} | {p['risk_left']} | {p['changed']} |")
    ref = sen["references"]
    flat = [p["lambda"] for p in sen["pareto"] if p["changed"] == 0]
    same = [p for p in sen["pareto"] if p["contained"] == ref["full_isolation_safe"]["contained"]]
    L += ["", f"References (fixed): full isolation (safe) contains {ref['full_isolation_safe']['contained']} with "
          f"{ref['full_isolation_safe']['services_down']} services down; per-machine rule contains "
          f"{ref['per_machine']['contained']} with {ref['per_machine']['services_down']} down and "
          f"{ref['per_machine']['silent_failures']} silent failures.", "",
          f"Reading: decisions are identical for every λ from {min(flat):g} to {max(flat):g}. Rejected (unsafe) decisions: "
          f"{max(p['rejected'] for p in sen['pareto'])} at every λ — the hard rule holds at all weights."]
    if same:
        p = same[0]
        L += [f" At λ={p['lambda']:g} Q-ACRS contains as many scenarios as full isolation (safe) "
              f"({p['contained']}) with {p['services_down']} services down instead of "
              f"{ref['full_isolation_safe']['services_down']}."]
    L += ["", "![trade-off](figures/fig1_tradeoff.png)", ""]

    # E3
    by = sca["by_departments"]
    L += ["## E3 — Scaling", "", "| Machines | Scenarios | Qubits mean | Qubits max | ZZ terms mean | 2-qubit gates (p=3, before routing) | Exact solve median (ms) | Annealing = exact |",
          "|---|---|---|---|---|---|---|---|"]
    for k in sorted(by, key=int):
        x = by[k]
        L.append(f"| {x['machines']} | {x['scenarios']} | {x['qubits_mean']:.1f} | {x['qubits_max']} | "
                 f"{x['quadratic_terms_mean']:.1f} | {x['two_qubit_gates_p3_mean']:.0f} | {x['exact_ms_median']:.1f} | "
                 f"{x['sa_matches_exact']}/{x['exact_available']} |")
    L += ["", "![scaling](figures/fig3_scaling.png)", ""]

    # E4
    L += ["## E4 — QAOA / CVaR over seeds, real 100-sample budget", ""]
    if qs:
        m = qs["summary"]; per = qs["per_seed"]
        L += [f"Seeds: {qs['seeds']}. Scenarios with a quantum step: {per[0]['scenarios']} "
              f"(hard ≥ 7 qubits: {per[0]['hard']}). Median and range over seeds:", "",
              "| Metric | Value |", "|---|---|",
              f"| Mean p_best at p=3 (chance one shot is optimal) | {rng(m['mean_p_best_p3'], True)} |",
              f"| Scenarios where best of 100 QAOA samples is optimal | {rng(m['hits_100_qaoa_mean'])} / {per[0]['scenarios']} |",
              f"| …same budget, simulated annealing 100 steps | {rng(m['hits_100_sa_100'])} / {per[0]['scenarios']} |",
              f"| …same budget, random 100 samples | {rng(m['hits_100_random'])} / {per[0]['scenarios']} |",
              f"| Hard scenarios: QAOA mean objective | {rng(m['hard_hits_100_qaoa_mean'])} / {per[0]['hard']} |",
              f"| Hard scenarios: QAOA CVaR objective | {rng(m['hard_hits_100_qaoa_cvar'])} / {per[0]['hard']} |",
              f"| Hard scenarios: annealing 100 steps | {rng(m['hard_hits_100_sa_100'])} / {per[0]['hard']} |",
              f"| Hard scenarios: random 100 | {rng(m['hard_hits_100_random'])} / {per[0]['hard']} |",
              f"| Unsafe samples drawn (all seeds; never-isolate devices are removed before QAOA, so this checks the pipeline) | {m['unsafe_samples_total']} |", "",
              "QAOA angle tuning (classical) is outside the 100-sample budget, which favours QAOA. Exact search and "
              "full annealing (5×4000 steps) find the optimum in 40/40. On 4-qubit problems random sampling does as well or better. Results are noiseless; real hardware adds noise. **No quantum advantage is claimed.**", "",
              "![qaoa](figures/fig4_qaoa_budget.png)", ""]
    else:
        L += ["Not finished yet (run `python -m qacrs.phase4c_seeds 0 1 2 3 4` then `--aggregate`).", ""]

    # E5, E6, E7
    L += ["## E5 — Blind scenarios", ""]
    if blind:
        for f in blind:
            d = json.loads(f.read_text()); x = d["summary"]["q_acrs"]
            L += [f"- `{f.name}`: {d['counts']['valid']}/{d['counts']['submitted']} valid; Q-ACRS contained "
                  f"{x['contained']}, escalated {x['escalated']}, silent {x['silent_failures']}, rejected "
                  f"{x['rejected_unsafe']}, services down {x['services_down']}; H1-v3: {d['h1_v3']['H1_v3_supported']}"]
    else:
        L += ["**Not run yet.** Kit ready: `qacrs/independent/` (guide, template, validator); code locked in "
              "`qacrs/independent/LOCK.json` before any blind scenario existed."]
    L += ["", "## E6 — Mock firewall adapter", "",
          "`qacrs/policy_executor.py`, tested in `tests/test_qacrs_v3.py` (valid policy, dry-run default, "
          "never-isolatable, two **different** approvers, unknown device, retry, retries exhausted → rollback, "
          "idempotency, rollback, escalation, refusal of any adapter marked real, append-only audit log). "
          "**Simulation only: no real firewall or network was used.**", "", "## E7 — IBM hardware", ""]
    if ibm:
        for f in ibm:
            d = json.loads(f.read_text())
            L += [f"- **Hardware** `{d['backend']}`, job `{d['job_id']}`, scenario `{d['scenario']}` ({d['qubits']} qubits, "
                  f"p={d['p']}, {d['shots']} shots): p_best real {100 * d['p_best_real']:.1f}% vs ideal "
                  f"{100 * d['p_best_ideal']:.1f}% vs random {100 * d['p_best_random']:.1f}%; safety gate on the most "
                  f"frequent answer: {d['most_frequent_real_decision']['safety_gate']['status']}."]
    else:
        L += ["**Not run in this round.** Script ready: `python -m qacrs.lesson4_ibm_scaled --check`, then "
              "`--dry-run`, then `--run` (pre-registered scenario `net12_h04`, 5 qubits). The earlier 3-qubit run "
              "(`ibm_marrakesh`, job `db0mcf6egvvc73bghe70`) is a previously recorded result."]
    L += ["", "## Limitations", "",
          "- Synthetic hospital networks and scenarios; weights are design assumptions (E2 shows decisions do not "
          "move within ±50% of each).",
          "- The escalation gate was designed on the development scenarios; generalisation needs the blind set.",
          "- No quantum advantage: classical exact and annealing solvers are faster and always optimal here.",
          "- The firewall adapter is a mock; no production integration was tested.", ""]
    return "\n".join(L)


def main():
    DOC.write_text(build())
    print(f"Saved: {DOC}")


if __name__ == "__main__":
    main()
