"""Build docs/qacrs/VERIFICATION_v2.md from the result files only (no number is typed by hand).

    cd backend && python -m qacrs.report_v2
"""
from __future__ import annotations

import json
from pathlib import Path

R = Path(__file__).parent / "results"
DOC = Path(__file__).resolve().parents[2] / "docs" / "qacrs" / "VERIFICATION_v2.md"


def load(p):
    return json.loads((R / p).read_text())


def qaoa_stats(p4, p4b):
    rows = [r for r in p4["rows"] if r.get("qubits", 0) > 0]
    hard = {r["scenario"]: r for r in p4b["rows"]}
    avg_best = sum(r["p3"]["p_best"] for r in rows) / len(rows)
    avg_rand = sum(r["p3"]["random"] for r in rows) / len(rows)
    found = sum(r["p3"]["hit_100"] > 0.99 for r in rows)
    hard_mean = sum(h["mean_p3"]["hit_100"] > 0.99 for h in hard.values())
    hard_cvar = sum(h["cvar_p3"]["hit_100"] > 0.99 for h in hard.values())
    easy_found = sum(r["p3"]["hit_100"] > 0.99 for r in rows if r["scenario"] not in hard)
    nonmono = sum(r["p2"]["p_best"] < r["p1"]["p_best"] - 1e-9 or r["p3"]["p_best"] < r["p2"]["p_best"] - 1e-9
                  for r in rows)
    ratio_mean = sum(h["mean_p3"]["ratio"] for h in hard.values()) / len(hard)
    ratio_cvar = sum(h["cvar_p3"]["ratio"] for h in hard.values()) / len(hard)
    return {"n": len(rows), "avg_best": avg_best, "avg_rand": avg_rand, "found": found, "n_hard": len(hard),
            "hard_mean": hard_mean, "hard_cvar": hard_cvar, "combined_cvar": easy_found + hard_cvar,
            "nonmono": nonmono, "ratio_mean": ratio_mean, "ratio_cvar": ratio_cvar}


def ibm_check(d):
    best = {tuple(x) for x in d["best_decisions"]}
    shots = sum(d["counts"].values())
    hit = sum(c for b, c in d["counts"].items() if tuple(int(ch) for ch in b[::-1]) in best) / shots
    return shots, hit


def pct(x):
    return f"{100 * x:.1f}%"


def build() -> str:
    p3_v1, p3_re = load("phase3_compare.json")["summary"], load("v2/rerun_of_v1/phase3_compare.json")["summary"]
    q_v1 = qaoa_stats(load("phase4_qaoa_sim.json"), load("phase4b_cvar.json"))
    q_re = qaoa_stats(load("v2/rerun_of_v1/phase4_qaoa_sim.json"), load("v2/rerun_of_v1/phase4b_cvar.json"))
    env = load("v2/rerun_of_v1/environment.json")
    ibm = load("lesson3_ibm.json"); shots, hit = ibm_check(ibm)
    c = load("v2/containment.json"); s, h1, meta = c["summary"], c["h1"], c["meta"]

    def same(a, b):
        return "✅ same" if a == b else "⚠️ differs"

    L = []
    L += ["# Q-ACRS — Verification report (v2)", "",
          "> Generated by `python -m qacrs.report_v2` from the JSON files in `backend/qacrs/results/`. "
          "Do not edit numbers by hand; re-run the script.", "",
          f"Containment run: {meta['date_utc']}, commit `{meta['git_commit']}`, Python {meta['python']}, "
          f"numpy {meta['numpy']}. Re-run environment: Python {env['python']}, numpy {env['numpy']}, "
          f"scipy {env['scipy']}.", "",
          "## 1. Are the v1 numbers reproducible?", "",
          "The unchanged v1 scripts were re-run in a second environment (`results/v2/rerun_of_v1/`). "
          "Original v1 files were not touched.", "",
          "| Claim (v1) | v1 file | Re-run | Verdict |", "|---|---|---|---|"]
    for k, label in (("full_isolation", "Full isolation"), ("per_machine", "Per-machine rule"), ("q_acrs", "Q-ACRS")):
        a, b = p3_v1[k], p3_re[k]
        L.append(f"| {label}: services down / unsafe / risk left | {a['services_down']} / {a['unsafe_decisions']} / "
                 f"{a['risk_left']} | {b['services_down']} / {b['unsafe_decisions']} / {b['risk_left']} | "
                 f"{same(a, b)} |")
    L += [f"| QAOA p=3: mean p_best over {q_v1['n']} scenarios | {pct(q_v1['avg_best'])} | {pct(q_re['avg_best'])} | "
          f"{same(round(q_v1['avg_best'], 3), round(q_re['avg_best'], 3))} |",
          f"| QAOA: scenarios with >99% chance of optimum in 100 shots | {q_v1['found']}/{q_v1['n']} | "
          f"{q_re['found']}/{q_re['n']} | {same(q_v1['found'], q_re['found'])} |",
          f"| CVaR on {q_v1['n_hard']} hard scenarios (mean → CVaR) | {q_v1['hard_mean']} → {q_v1['hard_cvar']} | "
          f"{q_re['hard_mean']} → {q_re['hard_cvar']} | {same(q_v1['hard_cvar'], q_re['hard_cvar'])} |",
          f"| All scenarios after CVaR | {q_v1['combined_cvar']}/{q_v1['n']} | {q_re['combined_cvar']}/{q_re['n']} | "
          f"{same(q_v1['combined_cvar'], q_re['combined_cvar'])} |",
          f"| IBM `{ibm['backend']}` job `{ibm['job_id']}`: chance one shot is optimal | {pct(ibm['hit_real'])} "
          f"(stored) | {pct(hit)} recomputed from the {shots} raw counts | "
          f"{same(round(ibm['hit_real'], 3), round(hit, 3))} |", "",
          "**Reading:** Phase 3 is exactly reproducible (it is deterministic). The QAOA/CVaR numbers move by about "
          "one scenario between environments because the angle optimiser (COBYLA) is sensitive to floating-point "
          "details; the direction of every conclusion is unchanged. From now on QAOA results must be reported as a "
          "range over several seeds/environments, not as a single number. The IBM figure was recomputed from the "
          "stored raw counts; the job itself can only be confirmed on IBM's side "
          "(`python -m qacrs.lesson3_ibm --job <id>` with the owner's account).", "",
          "## 2. What the v1 percentages actually measure", "",
          "| Name in v1 | Exact meaning | What it is NOT |", "|---|---|---|",
          "| `p_best` (e.g. 26.9%, 96.5%) | probability that ONE measurement returns an optimal decision of that "
          "scenario's QUBO | not detection accuracy, not a success rate of the defence |",
          "| \"found in 100 shots\" (31/38) | number of scenarios where 1−(1−p_best)^100 > 0.99, computed "
          "**analytically** from the state vector | not 100 real samples drawn |",
          "| `random` (3.3%) | share of all 2^n decisions that are optimal (blind guessing) | not a classical "
          "baseline solver; simulated annealing and brute force find the optimum 40/40 |",
          "| `ratio` | (worst − mean cost) / (worst − best) of the measured distribution | — |", "",
          f"Also found: in {q_re['nonmono']}/{q_re['n']} scenarios a deeper circuit (higher p) gave a LOWER p_best "
          "than a shallower one, so \"more depth is better\" is not guaranteed with this optimiser. On the hard "
          f"scenarios CVaR raises the chance of the optimum but lowers the average quality (ratio "
          f"{q_re['ratio_mean']:.3f} → {q_re['ratio_cvar']:.3f}); this is the expected CVaR trade-off and must be "
          "stated with the result.", "",
          "## 3. New: containment under the pre-registered criteria", "",
          "Criteria were committed before this code and these results: `docs/qacrs/PREREGISTRATION.md`. "
          "Same 40 scenarios, weights unchanged.", "",
          "| Method | Contained | of which need 2-person | Not contained | Rejected (unsafe) | Services down | "
          "Healthy machines isolated | Risk left |", "|---|---|---|---|---|---|---|---|"]
    names = {"full_isolation": "Full isolation (v1)", "full_isolation_safe": "Full isolation, safe (new)",
             "per_machine": "Per-machine rule", "q_acrs": "Q-ACRS"}
    for k, label in names.items():
        x = s[k]; st = x["status_counts"]
        L.append(f"| {label} | {x['contained']}/{x['scenarios']} | {st['CONTAINED_PENDING_APPROVAL']} | "
                 f"{st['NOT_CONTAINED']} | {st['REJECTED']} | {x['services_down']} | {x['healthy_isolated']} | "
                 f"{x['risk_left']} |")
    L += ["", "Secondary analysis (threshold for C2): " + "; ".join(
        f"{names[k]}: t=6 → {x['contained_at_secondary']['6']}, t=8 → {x['contained_at_secondary']['8']}"
        for k, x in s.items()) + ".", ""]

    rows = c["rows"]
    q_fail = [r for r in rows if r["q_acrs"]["verdict"]["status"] == "NOT_CONTAINED"]
    c2_crit = [r for r in q_fail if any(x.startswith("C2") for x in r["q_acrs"]["verdict"]["reasons"])]
    both = [r for r in q_fail if r["full_isolation_safe"]["verdict"]["status"] == "NOT_CONTAINED"]
    L += ["### Hypothesis H1", "",
          f"Rule as written in the pre-registration statement: {h1['rule']}.", "",
          f"- containment ratio Q-ACRS / safe full isolation = {h1['containment_ratio']} "
          f"(≥ 0.80: {'yes' if h1['containment_ok'] else 'no'})",
          f"- fewer services down: {'yes' if h1['fewer_services_down'] else 'no'}",
          f"- fewer healthy machines isolated: {'yes' if h1['fewer_healthy_isolated'] else 'no'} "
          f"({s['q_acrs']['healthy_isolated']} vs {s['full_isolation_safe']['healthy_isolated']})", "",
          f"**Result: H1 {'SUPPORTED' if h1['H1_supported'] else 'NOT SUPPORTED as written'}.** "
          "Honest note: the pre-registration has an internal inconsistency. Its hypothesis sentence includes "
          "\"isolates fewer healthy machines\", but its rejection rule names only containment (80%) and services "
          "down. The code applies the stricter sentence. Neither method isolated any healthy machine (a tie), so "
          "that part cannot be shown on this scenario set. By the rejection rule alone H1 would not be rejected. "
          "Both readings are reported; the pre-registration is not edited after the fact, and v3 must fix the "
          "wording before running.", "",
          "### Where Q-ACRS fails, and why", "",
          f"- **{len(c2_crit)} of {len(q_fail)} failures: a hacked critical server (database or domain controller) "
          "with risk ≥ 7 is only restricted.** In the QUBO, isolating the database or the domain controller takes "
          "down the services that need it, which outweighs its leftover risk, so the optimum never isolates it. This is a real "
          "weakness of the weights, not a solver error: "
          + ", ".join(f"`{r['scenario']}` {r['hacked']}" for r in c2_crit) + ".",
          f"- **{len(both)} failures are shared with safe full isolation:** a hacked device that may never be "
          "isolated (lab analyzer) has a link to the database. No method closes that path without isolating a "
          "healthy critical server. These are structural limits of the scenario, flagged for the device owner.",
          "- Q-ACRS never produced an unsafe decision and never isolated a healthy machine in this run.", "",
          "**Proposed v3 change (to be pre-registered, not applied here):** when a critical server is hacked with "
          "risk ≥ 7, the system must output `HUMAN_APPROVAL_REQUIRED` (two-person rule) instead of silently "
          "restricting it. This turns the " + str(len(c2_crit)) + " silent failures into explicit escalations.", "",
          "## 4. Mathematical checks (automated tests)", "",
          "`cd backend && python -m unittest tests.test_qacrs -v` checks, among others:", "",
          "- the BIG penalty: in every scenario where a never-isolate device is a variable, every decision that isolates it costs more "
          "than the most expensive decision without it, so weights can never outvote this rule;",
          "- problem reduction: on the 12-machine network the reduced QUBO has exactly the same optimum as the "
          "full 12-variable QUBO in all 20 scenarios;",
          "- QUBO ↔ Ising conversion is exact; vectorised and scalar cost agree; simulated annealing reaches the "
          "exact optimum in 40/40;",
          "- the safety layer rejects never-isolate devices, unknown machines, invalid risks, empty or "
          "wrong-network scenarios; critical servers need two people;",
          "- the summary in `containment.json` is recomputed from its raw rows, and no failure is counted as a "
          "success.", "",
          "## 5. Still open", "",
          "- Weight sensitivity, scaling study, independent scenarios, fair QAOA/CVaR/classical comparison over "
          "several seeds, mock firewall adapter (next phases).",
          "- Qiskit and IBM access must be checked on the owner's machine (not available in this environment).",
          "- The term \"40 scenarios\" is also used by the main ACRS engine for a different scenario set; the "
          "paper must name them differently.", ""]
    return "\n".join(L)


def main():
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(build())
    print(f"Saved: {DOC}")


if __name__ == "__main__":
    main()
