/**
 * Translates text generated by the backend (reasons, attack names, actions, checks, audit entries…).
 * English is the backend's source language, so `en` returns the text unchanged; `ar` translates it.
 * Proper names (hostnames, IPs, MITRE IDs, segments, product names) stay as they are.
 * Coverage is tested against every string the engines produce across the 40 scenarios (tr.test.ts).
 */
import type { Lang } from "./i18n";

const PHRASES: Record<string, string> = {
  // attack types
  "Account Compromise": "اختراق حساب",
  "Cloud Persistence": "تثبيت وجود في السحابة",
  "Command & Control": "اتصال بخادم تحكم (C2)",
  "Credential Dumping": "سرقة بيانات الاعتماد",
  "DNS Tunneling": "تهريب بيانات عبر DNS",
  "Data Exfiltration": "تسريب بيانات",
  "Ransomware": "برنامج فدية",
  "Lateral Movement": "تحرك جانبي",
  "Malicious Execution": "تنفيذ برنامج خبيث",
  "Suspicious Activity": "نشاط مشبوه",
  // entry paths and vectors
  "Cloud credential abuse": "إساءة استخدام بيانات اعتماد سحابية",
  "Compromised credentials": "بيانات اعتماد مخترقة",
  "Lateral movement from a peer": "تحرك جانبي من جهاز مجاور",
  "Phishing attachment": "مرفق بريد تصيّد",
  "Unknown (under investigation)": "غير معروف (قيد التحقيق)",
  "Web application exploitation": "استغلال ثغرة في تطبيق ويب",
  cloud: "السحابة", email: "البريد", identity: "الهوية", lateral: "تحرك جانبي", web: "الويب",
  // decision reasons (fixed)
  "Asset cannot be isolated (safety-critical / no agent): compensating controls only":
    "لا يمكن عزل هذا الأصل (حساس للسلامة أو بلا وكيل حماية): ضوابط تعويضية فقط",
  "Asset is inside an approved change window (risk -15)": "الأصل داخل نافذة تغيير معتمدة (خُصمت 15 نقطة من الخطورة)",
  "Asset not in CMDB: restrict the source IP at the edge only": "الجهاز غير مسجل في قائمة الأصول: تقييد عنوانه عند حافة الشبكة فقط",
  "Essential flows stay allowlisted; C2 and DNS are blocked at the network":
    "الاتصالات الأساسية تبقى مسموحة، ويُحظر خادم التحكم والنطاقات الخبيثة على مستوى الشبكة",
  "Full isolation needs two approvers": "العزل الكامل يحتاج موافقة شخصين مختلفين",
  "Ransomware fast path (T1486/T1490): contain before confidence gating":
    "المسار السريع لبرامج الفدية (T1486/T1490): الاحتواء فورًا دون انتظار اكتمال الثقة",
  "Restrict automatically; surgical isolation needs approval": "تقييد آلي الآن، والعزل الجراحي يحتاج موافقة",
  "Tier-0 emergency containment: restrictive actions only, authentication keeps running on the other controllers":
    "احتواء طارئ لـ Tier-0: إجراءات تقييدية فقط، والمصادقة مستمرة على وحدات التحكم الأخرى",
  "Tier-0: restrictive actions only; full isolation needs two approvers":
    "Tier-0: إجراءات تقييدية فقط، والعزل الكامل يحتاج موافقة شخصين",
  "Tier-0: enhanced monitoring, emergency containment needs two approvers":
    "Tier-0: مراقبة مشددة، والاحتواء الطارئ يحتاج موافقة شخصين",
  "Tier-1: surgical isolation, service continues on redundant nodes":
    "Tier-1: عزل جراحي، والخدمة مستمرة على الخوادم البديلة",
  "Tier-1 without redundancy: surgical isolation + degraded mode": "Tier-1 بلا خادم بديل: عزل جراحي مع تشغيل الخدمة بقدرة منخفضة",
  "Tier-2: full isolation, no human needed": "Tier-2: عزل كامل دون حاجة لتدخل بشري",
  "UEBA confirms abnormal behaviour despite the change window": "تحليل السلوك يؤكد نشاطًا غير طبيعي رغم نافذة التغيير",
  "UEBA shows no deviation beyond the change baseline: analyst confirmation required":
    "تحليل السلوك لا يُظهر انحرافًا عن المتوقع أثناء التغيير: يلزم تأكيد المحلل",
  // holds and escalations
  "Analyst verified: legitimate activity": "تحقق المحلل: نشاط مشروع",
  "Change window: confirm before remediation": "نافذة تغيير: يلزم التأكيد قبل الإصلاح",
  "Medium confidence: confirm or escalate before remediation": "ثقة متوسطة: أكّد أو صعّد قبل الإصلاح",
  "Non-isolatable asset: remediation needs the device owner / vendor": "أصل غير قابل للعزل: الإصلاح يحتاج مالك الجهاز أو المورّد",
  "Unknown asset: register it in the CMDB or escalate": "جهاز غير معروف: سجّله في قائمة الأصول أو صعّد الحادثة",
  "IoB: beacon to known C2 resumed (persistence survived remediation)":
    "عاد مؤشر الاختراق: الجهاز يتصل بخادم التحكم مجددًا (بقي أثر بعد الإصلاح)",
  // detection titles (fixed)
  "Unauthorized LSASS memory access": "وصول غير مصرح به إلى ذاكرة LSASS",
  "Ransomware behavior (mass rename / shadow copy deletion)": "سلوك برنامج فدية (إعادة تسمية جماعية وحذف النسخ الاحتياطية)",
  // memory guard
  "Tier-0 is never automated from memory": "لا تُطبَّق ذاكرة الاستجابة على Tier-0 أبدًا",
  "decision requires human approval; memory cannot override it": "القرار يحتاج موافقة بشرية، والذاكرة لا تتجاوزها",
  "pattern level is stronger than the tier policy allows": "مستوى النمط أشد مما تسمح به سياسة المستوى",
  "approved pattern within tier policy": "نمط معتمد ضمن سياسة المستوى",
  "awaiting engineer validation": "بانتظار اعتماد المهندس",
  "validated response": "استجابة مُتحقق منها",
  // factors
  signal_severity: "شدة الإشارات", source_correlation: "تعدد المصادر", ioc_reputation: "سمعة عنوان المهاجم",
  asset_sensitivity: "أهمية الأصل", behavior_anomaly: "سلوك غير طبيعي", blast_radius: "نطاق الانتشار المحتمل",
  independent_sources: "مصادر مستقلة", threat_intel: "استخبارات التهديد", evidence_strength: "قوة الأدلة",
  attribution_conflict: "تعارض في تحديد الجهاز", change_window: "نافذة تغيير",
  "combined detection strength": "قوة الكشف المجمّعة", "egress outside role profile": "اتصال خارجي لا يناسب دور الجهاز",
  "no IoC reputation": "لا توجد سمعة معروفة للعنوان", "no anomaly": "لا سلوك غير طبيعي", "no threat-intel match": "لا تطابق في استخبارات التهديد",
  "threat-intel confidence": "ثقة استخبارات التهديد", "unknown asset": "أصل غير معروف",
  // actions
  APPLY_MICROSEGMENTATION: "تطبيق عزل دقيق للشبكة", BLOCK_C2: "حظر خادم التحكم", CLOUD_SG_UPDATE: "تحديث قواعد الأمان السحابية",
  CORDON_NODE: "إيقاف جدولة العقدة", DNS_BLOCK: "حظر النطاق الخبيث", DRAIN_FROM_POOL: "إخراج الخادم من مجموعة الخدمة",
  ENABLE_ENHANCED_MONITORING: "تفعيل المراقبة المشددة", HARDEN_ENTRY_POINT: "تحصين نقطة الدخول", ISOLATE_ASSET: "عزل الأصل",
  PROTECT_DATABASE: "حماية قواعد البيانات", RESTRICT_NETWORK: "تقييد الشبكة", RESTRICT_SEGMENT_LATERAL: "منع التحرك داخل الشبكة الفرعية",
  REVOKE_SESSION: "إلغاء الجلسات النشطة", ROTATE_SECRETS: "تغيير كلمات السر والمفاتيح", SET_NETWORK_STAGE: "تحديد مرحلة العودة للشبكة",
  WITHDRAW_SERVICE_RECORD: "سحب سجل الخدمة", RUN_VERIFICATION: "تشغيل فحص التحقق",
  // action status
  succeeded: "نجح", failed: "فشل", released: "أُلغي", rolled_back: "تم التراجع", passed: "نجح", manual: "يدوي",
  // audit actions
  APPROVAL_RECORDED: "تسجيل موافقة", AUTOMATION_CONFIRMED: "تأكيد متابعة الأتمتة", AWAITING_CONFIRMATION: "بانتظار التأكيد",
  CHANGE_WINDOW_SET: "تعديل نافذة التغيير", DEMO_RESET: "إعادة ضبط العرض", ENTRY_POINT_HARDENED: "تحصين نقطة الدخول",
  ESCALATED_TO_EMERGENCY_QUEUE: "إحالة إلى طابور الطوارئ", EVENTS_CORRELATED: "ربط الأحداث", FALSE_POSITIVE_ROLLBACK: "إلغاء كإيجابية كاذبة",
  INCIDENT_DETECTED: "رصد حادثة", IOB_DURING_OBSERVATION: "عودة المؤشر أثناء المراقبة", LOGIN_FAILED: "فشل تسجيل الدخول",
  RESPONSE_PATTERN_APPLIED: "تطبيق نمط استجابة", RESPONSE_PATTERN_SAVED: "حفظ نمط استجابة", RESPONSE_PATTERN_APPROVED: "اعتماد نمط استجابة",
  RESPONSE_PATTERN_REJECTED: "رفض نمط استجابة", SIMULATION_STARTED: "بدء سيناريو محاكاة", THREAT_CONTAINED: "احتواء التهديد",
  THREAT_NEUTRALIZED: "تحييد التهديد", VERIFICATION_GATE_FAILED: "فشل بوابة التحقق", INCIDENT_CLOSED: "إغلاق الحادثة",
  STATE_CHANGED: "تغيير المرحلة", RE_ENTRY_STAGE: "مرحلة عودة للشبكة", "Engineer Mode command": "أمر من وضع المهندس",
  success: "نجح", SIMULATION: "محاكاة", ACRS: "ACRS",
  // checks
  "gate:autoruns_clean": "لا برامج تشغيل تلقائي مشبوهة", "gate:behavior_normal": "السلوك طبيعي", "gate:edr_running": "برنامج الحماية يعمل",
  "gate:evidence_intact": "الأدلة سليمة", "gate:firewall_policy": "سياسة الجدار الناري مطبقة", "gate:no_critical_vulns": "لا ثغرات حرجة",
  "gate:no_ioc": "لا مؤشرات اختراق", "gate:secrets_rotated": "تم تغيير كلمات السر", "gate:services_healthy": "الخدمات تعمل بشكل سليم",
  no_ioc: "لا مؤشرات اختراق", no_critical_vulns: "لا ثغرات حرجة", autoruns_clean: "لا برامج تشغيل تلقائي مشبوهة",
  services_healthy: "الخدمات سليمة", edr_running: "برنامج الحماية يعمل", evidence_intact: "الأدلة سليمة",
  firewall_policy: "سياسة الجدار الناري", secrets_rotated: "تغيير كلمات السر", behavior_normal: "السلوك طبيعي",
  "probe:internet egress from host": "الجهاز لا يصل إلى الإنترنت",
  "probe:soc-jump-01 -> host (investigation, inbound only)": "جهاز التحقيق يصل إلى الجهاز (دخول فقط)",
  "internet egress from host": "الجهاز لا يصل إلى الإنترنت",
  "soc-jump-01 -> host (investigation, inbound only)": "جهاز التحقيق يصل إلى الجهاز (دخول فقط)",
  // evidence kinds
  disk_image: "نسخة القرص", hash_manifest: "قائمة البصمات", memory_dump: "نسخة الذاكرة", network_pcap: "تسجيل حركة الشبكة",
  process_tree: "شجرة العمليات", timeline: "الخط الزمني",
  // reputation, impact, countries, cities, tags
  benign: "سليم", "known-bad": "خبيث مؤكد", malicious: "خبيث", suspicious: "مشبوه", unknown: "غير معروف", internal: "داخلي",
  high: "مرتفع", low: "منخفض", medium: "متوسط", critical: "حرج",
  DE: "ألمانيا", MD: "مولدوفا", NL: "هولندا", RO: "رومانيا", RU: "روسيا", US: "الولايات المتحدة", "??": "غير معروف",
  "Frankfurt (approx.)": "فرانكفورت (تقريبي)", "Amsterdam (approx.)": "أمستردام (تقريبي)", "Moscow (approx.)": "موسكو (تقريبي)",
  "Chisinau (approx.)": "كيشيناو (تقريبي)", "Bucharest (approx.)": "بوخارست (تقريبي)",
  "Saint Petersburg (approx.)": "سانت بطرسبرغ (تقريبي)", "Ashburn (approx.)": "آشبورن (تقريبي)",
  "Hosting / Tor exit": "استضافة / مخرج شبكة Tor", "Bulletproof hosting": "استضافة تتجاهل البلاغات", "VPS provider": "مزوّد خوادم افتراضية",
  Hosting: "استضافة", "Amazon AWS": "Amazon AWS", unattributed: "غير منسوب", "internal network": "الشبكة الداخلية",
  "C2 infrastructure": "بنية خوادم تحكم", "Exfiltration staging": "خادم تجميع بيانات مسرّبة", "Loader infrastructure": "بنية تنزيل برامج خبيثة",
  "Botnet C2": "خادم تحكم لشبكة روبوتات", "Scanner / C2": "ماسح / خادم تحكم", Suspicious: "مشبوه", "Cloud provider range": "نطاق مزوّد سحابي",
  "no match": "لا تطابق",
  // asset roles and environments
  "api-gateway": "بوابة API", "build-server": "خادم بناء", database: "قاعدة بيانات", "domain-controller": "وحدة تحكم المجال",
  "erp-app": "تطبيق ERP", "hr-app": "تطبيق الموارد البشرية", "k8s-control-plane": "لوحة تحكم Kubernetes", "k8s-node": "عقدة Kubernetes",
  "medical-device": "جهاز طبي", pki: "خادم الشهادات", "vpn-gateway": "بوابة VPN", "web-frontend": "واجهة ويب", workstation: "محطة عمل",
  "on-prem": "داخل المؤسسة", aws: "AWS", k8s: "Kubernetes",
  // UEBA metrics
  "DNS volume": "حجم طلبات DNS", "IAM API calls by instance role": "استدعاءات صلاحيات السحابة من دور الخادم",
  "IIS worker spawning shells": "خادم الويب يشغّل أوامر نظام", "VPN session volume": "حجم جلسات VPN",
  "control plane egress to the internet": "لوحة التحكم تتصل بالإنترنت", "database egress volume": "حجم البيانات الخارجة من قاعدة البيانات",
  "egress from appliance management plane": "اتصال خارجي من واجهة إدارة الجهاز", "first-ever internet egress": "أول اتصال بالإنترنت على الإطلاق",
  "first-ever internet egress from PKI": "أول اتصال بالإنترنت من خادم الشهادات", "first-ever internet egress from a DC": "أول اتصال بالإنترنت من وحدة تحكم المجال",
  "new outbound destination": "وجهة خارجية جديدة", "outbound bytes per hour": "حجم البيانات الخارجة في الساعة",
  "outbound calls from API tier": "اتصالات خارجية من طبقة API", "outbound connections to new external IPs": "اتصالات بعناوين خارجية جديدة",
  "process tree outside change baseline": "عمليات خارج المتوقع أثناء التغيير", "sign-in from new country and device": "دخول من دولة وجهاز جديدين",
  // API errors
  "Automation is not paused on this incident": "الأتمتة ليست متوقفة في هذه الحادثة",
  "Incident is already closed or rolled back": "الحادثة مغلقة أو ملغاة بالفعل",
  "Incident is closed": "الحادثة مغلقة", "Incident not found": "الحادثة غير موجودة",
  "Nothing is waiting for approval on this incident": "لا يوجد شيء بانتظار الموافقة في هذه الحادثة",
  "Pattern not found": "النمط غير موجود", "Asset not found": "الأصل غير موجود", "Unknown scenario": "سيناريو غير معروف",
  "Invalid username or password": "اسم المستخدم أو كلمة المرور غير صحيحة", "Ingest rate limit exceeded": "تجاوزت حد إرسال الأحداث",
  "Reset is only available in demo mode": "إعادة الضبط متاحة في وضع العرض فقط",
  "Internal Server Error": "خطأ داخلي في الخادم",
};

const LEVELS: Record<string, string> = {
  MONITOR: "مراقبة فقط", COMPENSATING: "ضوابط تعويضية", RESTRICT: "تقييد", EMERGENCY_RESTRICT: "احتواء طارئ",
  SURGICAL: "عزل جراحي", FULL_ISOLATION: "عزل كامل",
};

const STATES: Record<string, string> = {
  DETECT: "رصد", UNDERSTAND: "فهم", IDENTIFY_ENTRY: "نقطة الدخول", ATTRIBUTE_ASSET: "تحديد الأصل", RISK: "الخطورة",
  DECIDE: "القرار", CONTAIN: "احتواء", VERIFY: "تحقق", REMEDIATE: "إصلاح", HARDEN: "تحصين", OBSERVE: "مراقبة",
  RE_ENTRY: "عودة تدريجية", LEARN: "تعلّم", CLOSE: "مغلقة", PENDING_APPROVAL: "بانتظار الموافقة",
  ESCALATED: "طابور الطوارئ", ROLLED_BACK: "ملغاة", APPROVED: "معتمد", REJECTED: "مرفوض", PENDING_VALIDATION: "بانتظار المراجعة",
};

const SOURCES: Record<string, string> = {
  edr: "برنامج الحماية", firewall: "الجدار الناري", ndr: "مراقبة الشبكة", dns: "DNS", identity: "الهوية",
  cloud: "السحابة", ueba: "تحليل السلوك", threat_intel: "استخبارات التهديد",
};

function list(s: string, dict: Record<string, string> = PHRASES): string {
  return s.split(/,\s*/).map((x) => dict[x.trim()] ?? ar(x.trim())).join("، ");
}

const RULES: [RegExp, (...m: string[]) => string][] = [
  [/^Risk (\d+) \/ confidence (\d+)% on Tier-(\d) \(auto threshold (\d+)\)$/,
    (_, r, c, t, th) => `الخطورة ${r} والثقة ${c}% على Tier-${t} (عتبة الاحتواء الآلي ${th})`],
  [/^Confidence (\d+)% < (\d+)% \((\d+) independent sources?\): no automatic containment$/,
    (_, c, min, n) => `الثقة ${c}% أقل من ${min}% (عدد المصادر المستقلة: ${n}): لا احتواء آلي`],
  [/^Medium band \((\d+) <= risk < (\d+)\)$/, (_, lo, hi) => `خطورة متوسطة (بين ${lo} و${hi})`],
  [/^Risk (\d+) < (\d+): monitor and enrich$/, (_, r, lo) => `الخطورة ${r} أقل من ${lo}: مراقبة وجمع معلومات إضافية`],
  [/^Risk (\d+) < (\d+): monitor$/, (_, r, lo) => `الخطورة ${r} أقل من ${lo}: مراقبة فقط`],
  [/^(\d+) assets hit in (\S+): restrict SMB\/RDP inside this segment only$/,
    (_, n, seg) => `${n} أجهزة مصابة في الشبكة الفرعية ${seg}: منع مشاركة الملفات وسطح المكتب البعيد داخلها فقط`],
  [/^Circuit breaker: (\d+) automatic containments in 10 min, human approval required$/,
    (_, n) => `قاطع الحماية: ${n} حالات احتواء آلي مفتوحة خلال 10 دقائق، يلزم موافقة بشرية لمنع عزل جماعي`],
  [/^Response Memory: approved pattern (\w+) matched at ([\d.]+)% \(no confirmation pause\)$/,
    (_, id, s) => `ذاكرة الاستجابة: نمط معتمد (${id}) تطابق بنسبة ${s}%، لذا لا توقف للتأكيد`],
  [/^Isolation controller unavailable: (.+) not applied within the (\d+)s deadline$/,
    (_, cmds, s) => `أداة العزل لا تستجيب: لم يُطبَّق (${list(cmds)}) خلال مهلة ${s} ثانية`],
  [/^Verification Gate failed (\d+) times: (.+)$/, (_, n, checks) => `فشلت بوابة التحقق ${n} مرات: ${list(checks)}`],
  [/^retrying: \[(.+)\]$/, (_, c) => `إعادة المحاولة: ${list(c.replace(/'/g, ""))}`],
  [/^Outbound C2-like traffic to ([\d.]+):(\d+)(?: on (.+))?$/,
    (_, ip, port, h) => `اتصال خارجي يشبه خادم تحكم إلى ${ip}:${port}${h ? ` من ${h}` : ""}`],
  [/^Beaconing to ([\d.]+) every ~(\d+)s(?: on (.+))?$/, (_, ip, s, h) => `اتصال دوري بـ ${ip} كل ${s} ثانية تقريبًا${h ? ` من ${h}` : ""}`],
  [/^(\S+) spawned with network activity(?: on (.+))?$/, (_, p, h) => `${p} شُغّل مع نشاط شبكي${h ? ` على ${h}` : ""}`],
  [/^Lateral fan-out to (\d+) internal hosts(?: on (.+))?$/, (_, n, h) => `محاولة وصول إلى ${n} أجهزة داخلية${h ? ` من ${h}` : ""}`],
  [/^DNS tunneling via (\S+)(?: on (.+))?$/, (_, d, h) => `تهريب بيانات عبر DNS باستخدام ${d}${h ? ` من ${h}` : ""}`],
  [/^Large outbound transfer to ([\d.]+)(?: on (.+))?$/, (_, ip, h) => `نقل كمية كبيرة من البيانات إلى ${ip}${h ? ` من ${h}` : ""}`],
  [/^Impossible travel for (\S+)(?: on (.+))?$/, (_, u, h) => `دخول مستحيل جغرافيًا للمستخدم ${u}${h ? ` على ${h}` : ""}`],
  [/^IAM persistence API: (\S+)(?: on (.+))?$/, (_, api, h) => `استدعاء صلاحيات لتثبيت الوجود في السحابة: ${api}${h ? ` على ${h}` : ""}`],
  [/^Threat-intel match: (\S+)(?: on (.+))?$/, (_, ind, h) => `تطابق مع استخبارات التهديد: ${ind}${h ? ` على ${h}` : ""}`],
  [/^Behavioral anomaly: (.+?)(?: on ([A-Z0-9.-]+))?$/, (_, m, h) => `سلوك غير طبيعي: ${ar(m)}${h ? ` على ${h}` : ""}`],
  [/^(.+) on ([A-Z][A-Z0-9-]+|\d+\.\d+\.\d+\.\d+)$/, (_, what, h) => `${ar(what)} على ${h}`],
  [/^(\d+) detections combined \(noisy-OR\)$/, (_, n) => `${n} إشارات كشف مجتمعة`],
  [/^(\d+) independent sensors agree$/, (_, n) => `${n} أجهزة استشعار مستقلة متفقة`],
  [/^(\d+) independent sources?: (.+)$/, (_, n, s) => `${n} مصادر مستقلة: ${list(s, SOURCES)}`],
  [/^(\d+) peers, (\d+) dependents, criticality (\w+)$/,
    (_, p, d, c) => `${p} أجهزة مجاورة، ${d} أنظمة تعتمد عليه، أهمية ${PHRASES[c] ?? c}`],
  [/^IoC reputation (\d+)$/, (_, n) => `سمعة العنوان ${n}`],
  [/^UEBA deviation ([\d.]+)$/, (_, n) => `انحراف سلوكي ${n}`],
  [/^probe:host -> (.+)$/, (_, h) => `الجهاز لا يصل إلى ${h}`],
  [/^host -> (.+)$/, (_, h) => `الجهاز لا يصل إلى ${h}`],
  [/^observe:(\d+)$/, (_, n) => `فحص المراقبة ${n}`],
  [/^(\w+) (\d+)\/(\d+)$/, (_, lvl, a, b) => `${LEVELS[lvl] ?? lvl}: ${a} من ${b}`],
  [/^approved escalation to (\w+)$/, (_, lvl) => `موافقة على التصعيد إلى ${LEVELS[lvl] ?? lvl}`],
  [/^harden entry: (.+)$/, (_, e) => `تحصين نقطة الدخول: ${ar(e)}`],
  [/^containment (\w+): \[SIMULATED\] (\w+) applied to (.+)$/,
    (_, lvl, cmd, tgt) => `${LEVELS[lvl] ?? lvl}: [محاكاة] طُبّق «${PHRASES[cmd] ?? cmd}» على ${tgt}`],
  [/^containment (\w+): (.+) \(simulated\) unavailable: gave up after (\d+) attempts at the deadline$/,
    (_, lvl, tool, n) => `${LEVELS[lvl] ?? lvl}: أداة ${tool} (محاكاة) لا تستجيب، توقفت المحاولات بعد ${n} محاولات عند انتهاء المهلة`],
  [/^\[SIMULATED\] (\w+) applied to (.+)$/, (_, cmd, tgt) => `[محاكاة] طُبّق «${PHRASES[cmd] ?? cmd}» على ${tgt}`],
  [/^(.+) \(simulated\) unavailable: gave up after (\d+) attempts at the deadline$/,
    (_, tool, n) => `أداة ${tool} (محاكاة) لا تستجيب، توقفت المحاولات بعد ${n} محاولات`],
  [/^(.+) \(simulated\)$/, (_, tool) => `${tool} (محاكاة)`],
  [/^Approval is not possible in state (\w+)$/, (_, s) => `لا يمكن الموافقة في مرحلة «${STATES[s] ?? s}»`],
  [/^Pattern is already (\w+)$/, (_, s) => `النمط ${STATES[s] ?? s} بالفعل`],
  [/^Unknown command (\w+)$/, (_, c) => `أمر غير معروف: ${c}`],
  [/^(\S+) already approved (\w+): a different approver is required$/,
    (_, who, lvl) => `${who} وافق بالفعل على «${LEVELS[lvl] ?? lvl}»: يلزم شخص مختلف للموافقة الثانية`],
  [/^Tier-(\d)$/, (_, n) => `Tier-${n}`],
  [/^(MISP|OpenCTI): (.+)$/, (_, f, t) => `${f}: ${PHRASES[t.charAt(0).toUpperCase() + t.slice(1)] ?? PHRASES[t] ?? t}`],
];

function ar(s: string): string {
  if (s in PHRASES) return PHRASES[s];
  if (s in LEVELS) return LEVELS[s];
  if (s in STATES) return STATES[s];
  for (const [re, fn] of RULES) {
    const m = s.match(re);
    if (m) return fn(...m);
  }
  return s;
}

/** Readable English for codes the backend emits (commands, checks, factors, audit actions, evidence). */
const EN: Record<string, string> = {
  APPLY_MICROSEGMENTATION: "Apply micro-segmentation", BLOCK_C2: "Block C2 server", CLOUD_SG_UPDATE: "Update cloud security groups",
  CORDON_NODE: "Cordon node", DNS_BLOCK: "Block malicious domain", DRAIN_FROM_POOL: "Drain from service pool",
  ENABLE_ENHANCED_MONITORING: "Enable enhanced monitoring", HARDEN_ENTRY_POINT: "Harden entry point", ISOLATE_ASSET: "Isolate asset",
  PROTECT_DATABASE: "Protect databases", RESTRICT_NETWORK: "Restrict network", RESTRICT_SEGMENT_LATERAL: "Block movement inside the segment",
  REVOKE_SESSION: "Revoke active sessions", ROTATE_SECRETS: "Rotate passwords and keys", SET_NETWORK_STAGE: "Set re-entry stage",
  WITHDRAW_SERVICE_RECORD: "Withdraw service record", RUN_VERIFICATION: "Run verification",
  APPROVAL_RECORDED: "Approval recorded", AUTOMATION_CONFIRMED: "Automation confirmed", AWAITING_CONFIRMATION: "Awaiting confirmation",
  CHANGE_WINDOW_SET: "Change window updated", DEMO_RESET: "Demo reset", ENTRY_POINT_HARDENED: "Entry point hardened",
  ESCALATED_TO_EMERGENCY_QUEUE: "Sent to the emergency queue", EVENTS_CORRELATED: "Events correlated",
  FALSE_POSITIVE_ROLLBACK: "Rolled back as false positive", INCIDENT_DETECTED: "Incident detected",
  IOB_DURING_OBSERVATION: "Indicator returned during observation", LOGIN_FAILED: "Sign-in failed",
  RESPONSE_PATTERN_APPLIED: "Response pattern applied", RESPONSE_PATTERN_SAVED: "Response pattern saved",
  RESPONSE_PATTERN_APPROVED: "Response pattern approved", RESPONSE_PATTERN_REJECTED: "Response pattern rejected",
  SIMULATION_STARTED: "Simulation started", THREAT_CONTAINED: "Threat contained", THREAT_NEUTRALIZED: "Threat neutralized",
  VERIFICATION_GATE_FAILED: "Verification gate failed", INCIDENT_CLOSED: "Incident closed",
  signal_severity: "Signal severity", source_correlation: "Source correlation", ioc_reputation: "Attacker IP reputation",
  asset_sensitivity: "Asset sensitivity", behavior_anomaly: "Behaviour anomaly", blast_radius: "Blast radius",
  independent_sources: "Independent sources", threat_intel: "Threat intelligence", evidence_strength: "Evidence strength",
  attribution_conflict: "Asset attribution conflict", change_window: "Change window",
  no_ioc: "No indicators of compromise", no_critical_vulns: "No critical vulnerabilities", autoruns_clean: "No suspicious autoruns",
  services_healthy: "Services healthy", edr_running: "Endpoint protection running", evidence_intact: "Evidence intact",
  firewall_policy: "Firewall policy applied", secrets_rotated: "Secrets rotated", behavior_normal: "Behaviour normal",
  disk_image: "Disk image", hash_manifest: "Hash manifest", memory_dump: "Memory dump", network_pcap: "Network capture",
  process_tree: "Process tree", timeline: "Timeline", succeeded: "Succeeded", failed: "Failed", released: "Lifted",
  rolled_back: "Rolled back", "known-bad": "Known bad", "on-prem": "On-premises",
  "internet egress from host": "Host cannot reach the internet",
  "soc-jump-01 -> host (investigation, inbound only)": "Investigation host can reach the host (inbound only)",
  DE: "Germany", MD: "Moldova", NL: "Netherlands", RO: "Romania", RU: "Russia", US: "United States",
};

function en(s: string): string {
  if (s in EN) return EN[s];
  let m = s.match(/^gate:(\w+)$/);
  if (m) return EN[m[1]] ?? m[1];
  m = s.match(/^probe:(.+)$/);
  if (m) return EN[m[1]] ?? en(m[1]);
  m = s.match(/^host -> (.+)$/);
  if (m) return `Host cannot reach ${m[1]}`;
  m = s.match(/^observe:(\d+)$/);
  if (m) return `Observation check ${m[1]}`;
  m = s.match(/^Verification Gate failed (\d+) times: (.+)$/);
  if (m) return `Verification gate failed ${m[1]} times: ${m[2].split(/,\s*/).map((c) => EN[c] ?? c).join(", ")}`;
  m = s.match(/^Isolation controller unavailable: (.+) not applied within the (\d+)s deadline$/);
  if (m) return `Isolation tool not responding: ${m[1].split(/,\s*/).map((c) => EN[c] ?? c).join(", ")} not applied within the ${m[2]} s deadline`;
  return s;
}

/** Translate backend text for display. Empty values render as an em dash. */
export function tr(lang: Lang, s: string | null | undefined): string {
  if (s == null || s === "") return "—";
  return lang === "en" ? en(s) : ar(s);
}

/** Translate a comma-separated list or an array (commands, sources). */
export function trList(lang: Lang, items: string[] | null | undefined): string {
  if (!items || !items.length) return "—";
  return lang === "en" ? items.map((x) => en(x)).join(", ") : items.map((x) => ar(x)).join("، ");
}
